### ISSUE TITLE
Jinja templating for data and parameters

### ISSUE THREAD

**Issue by jagguli** [ggozad/behaving#65]
Having the ability to template parameters and data using jinja is very useful

I'm using the behave_http which implements this

 https://github.com/mikek/behave-http/blob/master/behave_http/utils.py#L18

with this I can target multiple deployments for example, and also handle states without having to write duplicate feature definitions. What are your thoughts ?

**Comment by ggozad** [comment]
I am not sure I understand properly. Can you please give me an example of how you use it? Is this useful for treating variables?

**Comment by millyto** [comment]
As you can see from the [behave_http link](https://github.com/mikek/behave-http/blob/master/behave_http/utils.py#L18), it contains code that uses jinja2 library, e.g.
`result = jinja2.Template(data).render(context.template_data)`
So what it does is that it uses data (context.text) as template and render against context.template_data which is the stored state. For example, you can have a behave configuration file called "behave.ini" which contains context.template_data for different deployments:
```
[behave]
format=plain
logging_clear_handlers=yes

[deployment.one]
id = first_deployment
server = https://one.com
other_data = one_1234

[deployment.two]
id = second_deployment
server = https://two.com
other_data = two_1234
```
Then you can write bdd test scenario using behave_http library as the example shown below:
```Python
Feature: feature name
    Scenario: some scenario
        Given: I am using server "{{server}}"
        When I make a POST request to "an_endpoint?id={{id}}"
        """
        {
            "data": "{{other_data}}"
        }
        """
        Then the response status should be 201
```
Instead of writing duplicate features/scenarios for different deployments, you can simply execute whichever deployment you like using the command line (with a little configuration in the main function), and jinja will render those variables wrapped around double curly braces against context.template_data, e.g. {{variable}}. For example, if deployment.one is executed then {{server}} will be rendered as https://one.com, {{id}} will be rendered as first_deployment, and {{other_data}} will be rendered as one_1234.

**Comment by ggozad** [comment]
To be honest I think this goes against the spirit of what BDD is about. Perhaps a personal choice, but I like to keep tests readable and with as little "code" like statements as possible.
I typically deal with things like config/settting up in python within the context of behave's pre/post processors. This works well for me and keeps my features clean and easy to understand. If it is not enough I make custom steps. I personally find it a lot easier to deal with these things in code rather than complicate syntax and sacrifice readability.

For personas I make extended use of persona variables. So for example:

```
Given Frodo as the persona
When I fill in "email" with "$email"
```

where the Frodo persona has an email property.
